name: CI/CD for Medusa Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to AWS ECS Fargate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, Push Image to ECR
      run: |
        docker build -t medusa-backend ./medusa-backend
        docker tag medusa-backend:latest ${{ steps.login-ecr.outputs.registry }}/medusa-backend:latest
        docker push ${{ steps.login-ecr.outputs.registry }}/medusa-backend:latest

    - name: Deploy via Terraform
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
